### ISSUE TITLE
Support for map

### ISSUE THREAD

**Issue by paulocoutinhox** [Xeverous/fuser#3]
Hi,

It has support for map?

Thanks.

**Comment by Xeverous** [comment]
No, but could be easily added. The question is whether there will be any problem with implementation invariants. Map seemed more complex than ordinary structs and therefore I initially left it out.

But thinking about it again, a map can be treated very analogically to a fusion sequence:

```cpp
struct member_struct
{
    std::string foo;
    std::string bar;
};
BOOST_FUSION_ADAPT_STRUCT(member_struct, foo, bar)

struct example_map
{
    int i;
    member_struct m;
};
BOOST_FUSION_ADAPT_STRUCT(example_map, i, m)
```

```cpp
struct example_fusion
{
    int i;
    std::map<std::string, std::string> m;
};
BOOST_FUSION_ADAPT_STRUCT(example_fusion, i, m)
```

Such JSON should then be compatible with both:

```json
{
    "i": 1,
    "m": {
        "foo": "foo_val",
        "bar": "bar_val"
    }
}
```

The only problem I see is that the map key has to serializable to a string. But I also want to support other types than `std::string`, eg a user-defined type that has a serializer to a string. Perhaps this could just forward the nested serialization to another template instantiation. Will try and see how it works.

**Comment by Xeverous** [comment]
Added in 00615fe.
